# -----------------------------------------------------------------------------
# Dockerfile for Rhasspy Pocketsphinx Service
# (https://github.com/rhasspy/rhasspy-asr-pocketsphinx-hermes)
#
# Requires Docker buildx: https://docs.docker.com/buildx/working-with-buildx/
# See scripts/build-docker.sh
#
# Builds a multi-arch image for amd64/armv6/armv7/arm64.
# The virtual environment from the build stage is copied over to the run stage.
# The Rhasspy source code is then copied into the run stage and executed within
# that virtual environment.
#
# Build stages are named build-$TARGETARCH$TARGETVARIANT, so build-amd64,
# build-armv6, etc. Run stages are named similarly.
#
# armv6 images (Raspberry Pi 0/1) are derived from balena base images:
# https://www.balena.io/docs/reference/base-images/base-images/#balena-base-images
#
# The IFDEF statements are handled by docker/preprocess.sh. These are just
# comments that are uncommented if the environment variable after the IFDEF is
# not empty.
#
# The build-docker.sh script will optionally add apt/pypi proxies running locally:
# * apt - https://docs.docker.com/engine/examples/apt-cacher-ng/ 
# * pypi - https://github.com/jayfk/docker-pypi-cache
# -----------------------------------------------------------------------------

FROM ubuntu:eoan as build-ubuntu

ENV LANG C.UTF-8

# IFDEF PROXY
#! RUN echo 'Acquire::http { Proxy "http://${PROXY}"; };' >> /etc/apt/apt.conf.d/01proxy
# ENDIF

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
        wget python3 python3-dev python3-setuptools python3-pip python3-venv \
        build-essential swig \
        curl ca-certificates

FROM build-ubuntu as build-amd64

# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

FROM build-amd64 as build

ENV APP_DIR=/usr/lib/rhasspy-asr-pocketsphinx-hermes
ENV BUILD_DIR=/build


COPY Makefile setup.py requirements.txt \
     ${APP_DIR}/

COPY scripts/ \
     ${APP_DIR}/scripts/

# IFDEF PYPI
#! ENV PIP_INDEX_URL=http://${PYPI}/simple/
#! ENV PIP_TRUSTED_HOST=${PYPI_HOST}
# ENDIF

RUN cd ${APP_DIR} && \
    make && \
    make install

# -----------------------------------------------------------------------------

FROM ubuntu:eoan as run-ubuntu

ENV LANG C.UTF-8

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        python3 libpython3.7 \
        sox

FROM run-ubuntu as run-amd64

# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------

FROM run-amd64

ENV APP_DIR=/usr/lib/rhasspy-asr-pocketsphinx-hermes
COPY --from=build ${APP_DIR}/.venv/ ${APP_DIR}/.venv/

# Copy source
COPY rhasspyasr_pocketsphinx_hermes/ ${APP_DIR}/rhasspyasr_pocketsphinx_hermes/
COPY bin/rhasspy-asr-pocketsphinx-hermes ${APP_DIR}/bin/

ENTRYPOINT ["bash", "/usr/lib/rhasspy-asr-pocketsphinx-hermes/bin/rhasspy-asr-pocketsphinx-hermes"]
