name: Build x64 Docker Images
on:
  push:
    branches: [ master, main ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: 'Build the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: soundflux/rhasspy/rhasspy-asr-pocketsphinx-hermes-amd64
          tags: latest
          dockerfile: Dockerfile-amd64
          tag_with_sha: true
          registry: registry.gitlab.com